wandb_version: 1

model_name:
  desc: null
  value: NousResearch/Llama-2-7b-hf
enable_fsdp:
  desc: null
  value: true
low_cpu_fsdp:
  desc: null
  value: false
run_validation:
  desc: null
  value: true
batch_size_training:
  desc: null
  value: 4
batching_strategy:
  desc: null
  value: packing
context_length:
  desc: null
  value: 4096
gradient_accumulation_steps:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 3
num_workers_dataloader:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0
gamma:
  desc: null
  value: 0.85
seed:
  desc: null
  value: 42
use_fp16:
  desc: null
  value: false
mixed_precision:
  desc: null
  value: true
val_batch_size:
  desc: null
  value: 1
peft_method:
  desc: null
  value: None
use_peft:
  desc: null
  value: false
output_dir:
  desc: null
  value: /mnt/checkpoints_disk/wiki-india-run-2/model
freeze_layers:
  desc: null
  value: false
num_freeze_layers:
  desc: null
  value: 1
quantization:
  desc: null
  value: false
one_gpu:
  desc: null
  value: false
save_model:
  desc: null
  value: true
dist_checkpoint_root_folder:
  desc: null
  value: /mnt/checkpoints_disk/wiki-india-run-2/FSDP/model
dist_checkpoint_folder:
  desc: null
  value: ft-model
save_optimizer:
  desc: null
  value: true
use_fast_kernels:
  desc: null
  value: true
wandb_project:
  desc: null
  value: llama-7b-full-ft-3
wandb_run_name:
  desc: null
  value: wiki-india-run-2
logging_steps:
  desc: null
  value: 25
sharding_strategy:
  desc: null
  value: ShardingStrategy.FULL_SHARD
checkpoint_type:
  desc: null
  value: StateDictType.SHARDED_STATE_DICT
fsdp_activation_checkpointing:
  desc: null
  value: true
fsdp_cpu_offload:
  desc: null
  value: false
pure_bf16:
  desc: null
  value: true
optimizer:
  desc: null
  value: AdamW
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700276975.112754
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 95
      - 98
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      6: 4.35.1
      8:
      - 5
      13: linux-x86_64
